### ISSUE TITLE
Saving settings script blocked by uBlock Origin

### ISSUE THREAD

**Issue by d3v1** [jrc9designstudio/statamic-google-analytics#6]
I had an issue saving the settings on this plugin. Have a quick look at my console log I realised that uBlock Origin blocks the save script.

I don't think this is something easily solved but it might be worth a line or two at the top of the form to warn people that ad blockers or script blockers could cause issues. It's the first time I've come across something like this within Statamic, I suspect it's because if the url having both Google and Analytics in it.

Thanks for writing this, it's really useful 👏

**Comment by jcohlmeyer** [comment]
Yes, I have noticed this issue as well. It is an issue with the patterns in uBlock Origin. So therefore the issue is with uBlock Origin and not this addon.

You can disable it for your site (probably a good idea anyways so you can test Google Analytics is actually working) for your site, or remove this rule form uBock Origin.

There is already a [note](https://github.com/jrc9designstudio/statamic-google-analytics#note) about this in the read me.

Glad you like the addon.
